### ISSUE TITLE
Gyroscope doesn't work well in Infamous: Second Son

### ISSUE THREAD

**Issue by r57zone** [r57zone/DualShock4-emulator#32]
Gyroscope doesn't work well in Infamous: Second Son

Related: http://www.youtube.com/watch?v=As4Jbf6Wu-M

**Comment by OGNEVVASILIJ** [comment]
r57zone вы пробовали для гироскопа модифицированный ViGEmBus ?[https://github.com/Davidobot/ViGEmBus](url)
У меня не как не получается его собрать.

**Comment by r57zone** [comment]
@OGNEVVASILIJ, Support for the gyroscope appeared a long time ago, it may not work very well, but I still don’t know how to fully implement it correctly. 
https://github.com/r57zone/DualShock4-emulator#gyroscope

Ru: Поддержка гироскопа появилась давно, работает может не совсем хорошо, но я пока не знаю как до конца правильно реализовать его. 
https://github.com/r57zone/DualShock4-emulator/blob/master/README.RU.md#гироскоп

**Comment by OGNEVVASILIJ** [comment]
Я переназначил на оси xbox пада и пробовал в Astro’s Playroom ps5 PS Remote Play так оси wAccelX, Y, Z прекрасно работают а wGyroX, Y, Z не реагируют.

**Comment by GenaXUS** [comment]
Кто-нибудь может сделать полноценный гайд как пройти эпизоды с граффити и подниманием машины?

**Comment by the-maazu** [comment]
> passed the initial phase base contantly moving the phone. It seems orientation is centering itself so I have to constantly move the phone to replicate vertical holding of the ds4

I went through the code I see nothing on "orientation", can you confirm if an actual DS4 Controller sends report on orientation. This could be why the motion keeps resetting since orientation is stuck. freePIE does output orientation data. 

Accelerometer and gyroscope measure transient effects acceleration and velocity, which resets and stays pretty much the same when the device is at rest.

Orientation on the other hand is a permanent until the device changes orientation of course.
