### ISSUE TITLE
Feature: HideCursorAfterStart=1 by default

### ISSUE THREAD

**Issue by goloskokovic** [r57zone/DualShock4-emulator#40]
To hide the cursor after startup, change HideCursorAfterStart to 1, to restore the cursor, close the program by pressing "ALT" + "ESCAPE" or "~".

This is not intuitive.

**Comment by r57zone** [comment]
This is necessary so that people understand how this trick works, if done by default, people may panic. I will probably need to add a description of this to the program interface.

**Comment by goloskokovic** [comment]
Make available to show/hide cursor by pressing ["some key"] on the keyboard.

**Comment by r57zone** [comment]
there is a problem that cannot hide and return the cursor multiple times, so I had to do this

**Comment by r57zone** [comment]
![](https://user-images.githubusercontent.com/9499881/147851831-738fd179-0a13-4f65-8688-a0fa0831bc86.png)
I added a button to hide the cursor, it will probably be a little more convenient now. Unfortunately, you cannot constantly turn it on and off due to the peculiarities of changing the cursor. but can press it once to quickly hide it for the game after the settings.

**Comment by goloskokovic** [comment]
your work is greatly appreciated
